# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-ObjScanner
version:      2.012
version_from: ObjScanner.pm
installdirs:  site
requires:
    Scalar::Util:                  1.01
    Tk:                            0
    Tk::Adjuster:                  0
    Tk::HList:                     0
    Tk::ROText:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
